// The repo's one TypeScript lint gate (a pre-launch review found nothing
// but the type checker was enforced for TS, Swift or Kotlin -- while Rust runs
// `clippy --all-targets -- -D warnings`).
//
// One config for every TS area, with `files:` overrides per area. The eleven
// npm installs under apps/ and packages/ keep their own dependencies;
// `projectService: true` resolves each file to its *own* nearest tsconfig, so
// no area needs `parserOptions` here.
//
// **This gate is not a compiler, and passing it is not "the code compiles".**
// On 2026-09-20 `packages/web/src/perf.ts` passed `npm run lint` while `tsc`
// rejected it, because a repo-wide `--fix` had deleted a `Navigator`
// assertion this config judged unnecessary and that package's own tsconfig
// needs. Only the closing run caught it, and only because it compiles the
// packages. Run `tsc` beside the gate, never instead of it.
//
// Why ESLint and not Biome, which would be faster and need no install:
// `no-floating-promises` and `no-misused-promises` are **type-aware**, and an
// un-awaited rejection is the class of bug this codebase has actually shipped
// -- S9 was `router.open(await f.text(), …)` in an un-caught async handler, so
// an unreadable file made the Studio look like it ignored the tap. Biome
// cannot do type-aware rules, so it would miss exactly that.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";

// `_name` already means "deliberately unused" throughout this repo
// (`specDocument.ts`'s `([_s, _b, _v]) => …`, the RN test stub's
// `constructor(_module)`). Telling the rule the convention is the honest fix;
// the code was already saying it. Shared so the TS and plain-JS tiers cannot
// drift apart -- `@typescript-eslint/no-unused-vars` needs no type
// information, so it survives `disableTypeChecked` and has to be configured in
// both places or it is an error in one and a warning in the other.
const unusedVars = [
  "error",
  {
    argsIgnorePattern: "^_",
    varsIgnorePattern: "^_",
    caughtErrorsIgnorePattern: "^_",
    destructuredArrayIgnorePattern: "^_",
  },
];

export default tseslint.config(
  {
    // Every ignore here is a reason, not a preference.
    ignores: [
      // Build output and caches.
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.next/**",
      "**/out/**",
      "**/.build/**",
      "target/**",
      "**/.gradle/**",
      "**/DerivedData/**",
      // A harness run against an upstream checkout (scripts/oracle/README.md): it
      // imports that repository's untyped modules by path, so type-aware rules can
      // only report `any`. Its correctness is its byte-for-byte self-check.
      "scripts/oracle/**",
      // Code generated from spec/parameters.json. Staleness is already a hard
      // failure via `node scripts/codegen/generate.mjs --check` in CI, and
      // linting a generator's output only ever edits the wrong file.
      "**/generated/**",
      "packages/web/src/element-typed.ts",
      // wasm-pack's output (sinua_core*.js/.d.ts/.wasm): regenerated by
      // `packages/core: npm run build` on every CI run.
      "packages/core/pkg/**",
      // voice-adapters' compile harness for the docs' samples: its own
      // tsconfigs (tsconfig.{web,rn}.json), already checked by
      // scripts/docs/check-snippets.mjs and check-code-snippets.sh, and
      // excluded by apps/site/tsconfig.json too.
      "apps/site/snippets/**",
      // Copies of packages/{ios,android}'s shared native source, refreshed by
      // packages/react-native/build.sh. Lint the source, not the copy.
      "packages/react-native/ios/**",
      "packages/react-native/android/**",
      // Example apps with their own toolchains and their own typecheck step
      // (`npm run typecheck` in apps/examples/web-component).
      "apps/examples/**",
      "packages/react-native/example/**",
      "apps/fx-bench-web/**",
    ],
  },

  js.configs.recommended,

  // --- Tier 1: TypeScript, with type information -------------------------
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    languageOptions: {
      parserOptions: {
        projectService: {
          // Linted without a project: real source that no tsconfig `include`
          // covers. Type-aware rules are simply off for these files.
          allowDefaultProject: [
            "apps/*/vite.config.ts",
            "packages/web/example/main.tsx",
            "packages/web/types/react.d.ts",
            "packages/web/types/solid.d.ts",
            "packages/web/types/svelte.d.ts",
            "packages/web/types/vue.d.ts",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // `tsc` already resolves every identifier, and it does it better --
      // typescript-eslint's own guidance is to leave this to the compiler.
      // Left on, it reports every DOM and Node global as undefined.
      "no-undef": "off",
      // Core `no-unused-vars` off in favour of the TS-aware one, which
      // understands type-only imports and enum members.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": unusedVars,
    },
  },

  // --- Tier 2: the two React areas ---------------------------------------
  {
    files: ["apps/*/src/**/*.{ts,tsx}", "apps/site/**/*.{ts,tsx}", "packages/web/src/**/*.tsx"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // `exhaustive-deps` is advice, not a contract: several deliberate
      // single-run effects in an app (a frame loop, a one-time
      // storage read) are correct with a narrow dep list, and a blanket
      // autofix there would change behaviour. Kept visible, not blocking.
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // --- Tier 3: loose .mjs/.cjs, which are in no tsconfig project ---------
  // Config and build scripts (next.config.mjs, postcss.config.mjs,
  // scripts/**). Syntax and correctness rules apply; type-aware ones cannot.
  {
    files: ["**/*.{mjs,cjs,js}"],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      sourceType: "module",
      ecmaVersion: 2023,
      // These are Node scripts: `process`, `console`, `URL`, `fetch`. Some
      // also touch DOM APIs -- `packages/core/scripts/gen-voice-golden.mjs`
      // uses `OfflineAudioContext`, and the materials comparison script uses
      // `Image`/`document` -- so both global sets apply. Without this,
      // `no-undef` reports every one of them.
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      // Node scripts legitimately use console as their output.
      "no-console": "off",
      // A `.cjs` file uses `require` by definition.
      "@typescript-eslint/no-require-imports": "off",
      // Same rule, same convention as the TS tier -- see `unusedVars`.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": unusedVars,
    },
  },

  // --- Adopted debt, with a count and an owner ---------------------------
  // The rules that fire under packages/, whose files belong to the families
  // and voice-adapters seats -- demoted here rather than edited by this seat.
  // Each line is a debt with an owner and a count, not a policy: delete the
  // line when its count reaches zero. That is the ratchet. A violation of any
  // *other* rule is a hard failure from day one, and so is a new violation
  // anywhere outside packages/.
  //
  // Counts are what **this config** reports (`npm run lint`), 2026-09-20 --
  // not what a per-area probe reports. They differ, and the difference is not
  // noise: type-aware results depend on which tsconfig and which installed
  // node_modules are in play, so linting `packages/voice` from the repo root
  // and from inside `packages/voice` can disagree about, say, whether an
  // assertion is unnecessary. Re-measure with the gate, never with a probe.
  //
  // `no-unnecessary-type-assertion` is **off** here rather than `warn`, and
  // that is the important line in this block. `--fix` rewrites warnings too,
  // so `warn` was never protection -- it is what let a repo-wide fix delete
  // casts in four files across three seats and break packages/web's build. A
  // rule whose verdict changes with the vantage point (root vs inside the
  // package) has no business being enforced, or auto-fixed, from the root.
  //
  //   no-unsafe-assignment           10  (core 8, voice 1, web 1)
  //   no-redundant-type-constituents  9  (web 7, core 2)
  //   no-unused-vars                  3  (web 2, core 1)
  //   no-unsafe-argument              3  (core 1, react-native 1, web 1)
  //   no-floating-promises            2  (voice)
  //   require-await                   2  (voice 1, web 1)
  //   no-unsafe-call                  1  (web)
  //
  // Taken from a **settled** tree: 188 files inspected, 38 warnings, 0 errors,
  // identical across two consecutive runs. Do not re-measure while anything is
  // installing or building -- mid-`npm ci` this same command reported 269,
  // because unresolved `@sinua/*` types make every import an error type and
  // the `no-unsafe-*` family fires on all of them. The count is a property of
  // the tree's build state as much as of the code.
  //   no-unnecessary-type-assertion  off (see above -- not a count)
  {
    // TS only: these rules need type information, and re-listing them for
    // `.mjs` under packages/ would re-enable type-aware linting on files that
    // tier 3 deliberately exempted.
    files: ["packages/**/*.{ts,tsx,mts,cts}"],
    rules: {
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-redundant-type-constituents": "warn",
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/require-await": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
    },
  },
  {
    // Not type-aware, so it is safe to demote across every extension under
    // packages/ -- `compare.cjs`'s unused `k` is the plain-JS one.
    files: ["packages/**"],
    rules: { "@typescript-eslint/no-unused-vars": ["warn", unusedVars[1]] },
  },
);
