#!/usr/bin/env node
// The SwiftPM distribution trees, generated from packages/ios* (nothing hand-copied).
//
// SwiftPM resolves a remote package by its repository and reads Package.swift from
// the root, while ours live in packages/ios, packages/ios-livekit and
// packages/ios-openai. So each becomes its own repository under the GitHub org:
//
//   sinua-swift          Sinua, SinuaVoice, CoreEngine, SinuaGeminiLive, SinuaElevenLabs
//   sinua-swift-livekit  SinuaLiveKit  (pulls LiveKit's SDK)
//   sinua-swift-openai   SinuaOpenAI   (pulls WebRTC)
//
// Three repositories, not one: SwiftPM fetches every dependency a package declares,
// so an app that only draws must not download LiveKit or WebRTC.
//
// In each tree: the root Package.swift, the Swift sources, LICENSE / NOTICE / README.
// The engine is a binary target by URL (the zip on sinua-swift's GitHub release) and
// checksum; the vendor packages depend on sinua-swift at exactly this version. Test
// targets stay in the monorepo.
//
//   node scripts/release/swift-dist.mjs <out dir> <version> <checksum> [--local <zip>]
//
// `--local <zip>` writes the same trees with the binary target pointed at a local zip
// and the vendor packages at the sibling tree by path -- the only differences from the
// URL form -- so a dry run can build them.
import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, resolve } from "node:path";

const root = fileURLToPath(new URL("../../", import.meta.url));
const [outArg, version, checksum, flag, localZip] = process.argv.slice(2);
if (!outArg || !version || !checksum) {
  console.error("usage: swift-dist.mjs <out dir> <version> <checksum> [--local <zip>]");
  process.exit(2);
}
const out = resolve(outArg);
const local = flag === "--local" ? resolve(localZip) : null;
const org = process.env.SINUA_GITHUB_ORG ?? "https://github.com/sinua-dev";
const zipName = "core_engineFFI.xcframework.zip";
const zipUrl = `${org}/sinua-swift/releases/download/${version}/${zipName}`;

const HEADER = (from) =>
  `// swift-tools-version:5.9\n// Generated by scripts/release/swift-dist.mjs from ${from} at version ${version}.\n// Don't edit here: change the monorepo and release again.\n`;

function removeTestTargets(manifest) {
  // `.testTarget(` ... `),` blocks, balanced on parentheses.
  let s = manifest;
  for (;;) {
    const i = s.indexOf(".testTarget(");
    if (i < 0) return s;
    let depth = 0, j = i + ".testTarget".length;
    for (; j < s.length; j++) {
      if (s[j] === "(") depth++;
      else if (s[j] === ")" && --depth === 0) break;
    }
    let end = j + 1;
    if (s[end] === ",") end++;
    const lineStart = s.lastIndexOf("\n", i) + 1;
    const lineEnd = s.indexOf("\n", end);
    s = s.slice(0, lineStart) + s.slice(lineEnd + 1);
  }
}

function body(manifest) {
  // Drop the original tools-version line and leading comments; keep the rest.
  return manifest.replace(/^\/\/ swift-tools-version:[^\n]*\n/, "");
}

function tree(name, fromDir, transform) {
  const dir = join(out, name);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  cpSync(join(root, fromDir, "Sources"), join(dir, "Sources"), { recursive: true });
  for (const f of ["LICENSE", "NOTICE", "THIRD_PARTY_LICENSES", "README.md"])
    if (existsSync(join(root, fromDir, f))) cpSync(join(root, fromDir, f), join(dir, f));
  const manifest = readFileSync(join(root, fromDir, "Package.swift"), "utf8");
  const next = transform(body(manifest));
  writeFileSync(join(dir, "Package.swift"), HEADER(fromDir) + next);
  return dir;
}

// SwiftPM wants a local binary target's path relative to the package root, so the
// local form carries a copy of the zip inside the tree.
const binary = local
  ? `.binaryTarget(name: "core_engineFFI", path: "${zipName}")`
  : `.binaryTarget(\n            name: "core_engineFFI",\n            url: "${zipUrl}",\n            checksum: "${checksum}"\n        )`;
const sinuaSwift = local
  ? `.package(name: "sinua-swift", path: "${join(out, "sinua-swift")}")`
  : `.package(url: "${org}/sinua-swift", exact: "${version}")`;

const made = [];
const sinuaDir = tree("sinua-swift", "packages/ios", (m) => {
    const b = '.binaryTarget(name: "core_engineFFI", path: "core_engineFFI.xcframework")';
    if (!m.includes(b)) throw new Error("packages/ios/Package.swift: the binary target line moved; update swift-dist.mjs");
    return removeTestTargets(m.replace(b, binary));
});
if (local) cpSync(local, join(sinuaDir, zipName));
made.push(sinuaDir);
for (const [name, from] of [["sinua-swift-livekit", "packages/ios-livekit"], ["sinua-swift-openai", "packages/ios-openai"]]) {
  made.push(
    tree(name, from, (m) => {
      if (!m.includes('.package(path: "../ios")')) throw new Error(`${from}/Package.swift: the ../ios dependency moved; update swift-dist.mjs`);
      return m.replace('.package(path: "../ios")', sinuaSwift).replaceAll('package: "ios"', 'package: "sinua-swift"');
    }),
  );
}
console.log(`swift-dist: ${made.length} trees in ${out}${local ? " (local zip)" : ""}`);
