// Platform parity for the web/wasm build: every case in
// spec/sinua-golden.json, rendered through the same `frameWithOverrides`
// the web Studio uses, must match the frozen vectors. The reference checker
// is crates/core_engine/tests/sinua_golden.rs; the rules here mirror it
// (counts, dots strict with a nearest-neighbour fallback, lines and
// polylines strict, the file's own tolerance).
//
// What this proves: that V8's wasm execution of the engine reproduces the
// native Rust output -- a cross-platform lock. It does NOT prove the output
// is right (the set was generated by this engine; see docs/testing.md).
//
// SINUA_GOLDEN_PATH overrides the file (used for the negative check when
// this test was written; normally unset).

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { frameWithOverrides } from "../dist/index.js";

const path =
  process.env.SINUA_GOLDEN_PATH ?? fileURLToPath(new URL("../../../spec/sinua-golden.json", import.meta.url));
const golden = JSON.parse(readFileSync(path, "utf8"));
const TOL = golden.tolerance;
const DOT = 8;
const LINE = golden.specVersion >= "1.1.0" ? 9 : 7; // 1.1.0 added line saturation/hue

const dotRows = (f) => f.dots.map((d) => [d.x, d.y, d.z, d.r, d.white, d.a, d.saturation, d.hue]);
const chunks = (flat, n) => Array.from({ length: flat.length / n }, (_, i) => flat.slice(i * n, i * n + n));
const near = (a, b) => Math.abs(a - b) < TOL;

/** Mirrors `nearest_match_ok` in sinua_golden.rs (z-sort tie-break reordering). */
function nearestMismatch(got, exp) {
  const used = new Array(exp.length).fill(false);
  for (let i = 0; i < got.length; i++) {
    let best = -1;
    let bestD = Infinity;
    for (let j = 0; j < exp.length; j++) {
      if (used[j]) continue;
      let d = 0;
      for (let k = 0; k < DOT; k++) d += (got[i][k] - exp[j][k]) ** 2;
      if (d < bestD) [best, bestD] = [j, d];
    }
    if (best < 0) return `dot[${i}] has no golden dot left`;
    used[best] = true;
    for (let k = 0; k < DOT; k++) {
      if (!near(got[i][k], exp[best][k])) return `dot[${i}] field ${k}: expected ${exp[best][k]}, got ${got[i][k]}`;
    }
  }
  return null;
}

test(`wasm matches all ${golden.cases.length} sinua golden cases`, () => {
  assert.ok(golden.cases.length > 0);
  for (const c of golden.cases) {
    const f = frameWithOverrides(c.state, c.size, c.t, c.overrides);
    assert.ok(f, `${c.key}: state did not resolve`);
    assert.equal(f.dots.length, c.dotCount, `${c.key}: dot count`);
    assert.equal(f.lines.length, c.lineCount, `${c.key}: line count`);
    assert.equal(f.polylines.length, c.polylineCount, `${c.key}: polyline count`);
    if (c.colorMode !== undefined) assert.equal(f.colorMode, c.colorMode, `${c.key}: colorMode`);

    const got = dotRows(f);
    const exp = chunks(c.dots, DOT);
    const strict = got.every((g, i) => g.every((v, k) => near(v, exp[i][k])));
    if (!strict) {
      const err = nearestMismatch(got, exp);
      assert.equal(err, null, `${c.key}: ${err}`);
    }

    f.lines.forEach((l, i) => {
      [l.x1, l.y1, l.x2, l.y2, l.white, l.a, l.w, l.saturation, l.hue].slice(0, LINE).forEach((v, k) => {
        const e = c.lines[i * LINE + k];
        assert.ok(near(v, e), `${c.key}: line[${i}].${k}: expected ${e}, got ${v}`);
      });
    });
    f.polylines.forEach((p, i) => {
      const g = c.polylines[i];
      [p.white, p.a, p.w, p.saturation, p.hue].forEach((v, k) =>
        assert.ok(near(v, g.style[k]), `${c.key}: polyline[${i}].style[${k}]: expected ${g.style[k]}, got ${v}`)
      );
      assert.equal(p.points.length * 2, g.points.length, `${c.key}: polyline[${i}] vertex count`);
      p.points.forEach((q, j) => {
        assert.ok(near(q.x, g.points[j * 2]), `${c.key}: polyline[${i}].pt[${j}].x`);
        assert.ok(near(q.y, g.points[j * 2 + 1]), `${c.key}: polyline[${i}].pt[${j}].y`);
      });
      // spec 1.6.0: per-vertex hues, absent = none.
      const hues = p.hues ?? [];
      assert.equal(hues.length, (g.hues ?? []).length, `${c.key}: polyline[${i}] hue count`);
      hues.forEach((h, j) => assert.ok(near(h, g.hues[j]), `${c.key}: polyline[${i}].hues[${j}]`));
    });

    // spec 1.2.0: fills and effect runs (only cases that have them carry them).
    const fills = f.fills ?? [];
    assert.equal(fills.length, (c.fills ?? []).length, `${c.key}: fill count`);
    fills.forEach((x, i) => {
      const g = c.fills[i];
      const cmp = (label, got, exp) => {
        assert.equal(got.length, exp.length, `${c.key}: fill[${i}].${label} length`);
        got.forEach((v, k) => assert.ok(near(v, exp[k]), `${c.key}: fill[${i}].${label}[${k}]: expected ${exp[k]}, got ${v}`));
      };
      cmp("style", [x.white, x.a, x.saturation, x.hue, x.blur, x.blend], g.style);
      cmp("points", x.points.flatMap((q) => [q.x, q.y]), g.points);
      // spec 1.3.0: holes (absent = none).
      const xh = x.holes ?? [];
      const gh = g.holes ?? [];
      assert.equal(xh.length, gh.length, `${c.key}: fill[${i}] hole count`);
      xh.forEach((ring, h) => cmp(`holes[${h}]`, ring.flatMap((q) => [q.x, q.y]), gh[h]));
      assert.equal(x.gradient === null, g.gradient === null, `${c.key}: fill[${i}] gradient`);
      if (x.gradient) {
        assert.equal(x.gradient.kind, g.gradient.kind, `${c.key}: fill[${i}] kind`);
        cmp("gradient.geom", [x.gradient.x0, x.gradient.y0, x.gradient.x1, x.gradient.y1, x.gradient.r], g.gradient.geom);
        cmp("gradient.stops", x.gradient.stops.flatMap((s) => [s.offset, s.white, s.a, s.saturation, s.hue]), g.gradient.stops);
      }
    });
    const eff = (f.effects ?? []).flatMap((e) => [e.target, e.start, e.count, e.blur, e.blend]);
    const geff = c.effects ?? [];
    assert.equal(eff.length, geff.length, `${c.key}: effect count`);
    eff.forEach((v, k) => assert.ok(near(v, geff[k]), `${c.key}: effects[${k}]`));
  }
});
