import Foundation
import XCTest

@testable import CoreEngine

/// Platform parity against `spec/sinua-golden.json` -- all 210 cases of the
/// 25 states upstream's `spec/orbs-golden.json` doesn't cover, run through
/// the real UniFFI boundary (Swift -> C -> Rust -> C -> Swift) on Apple's
/// float/libm. The reference checker is
/// `crates/core_engine/tests/sinua_golden.rs`; the rules mirror it
/// (counts, dots strict with a nearest-neighbour fallback, lines and
/// polylines strict, the file's own tolerance).
///
/// A cross-platform lock, not a correctness proof: the set was generated by
/// this engine (see docs/testing.md). The file is read from the repo via
/// `#filePath` rather than bundled as a SwiftPM resource -- `Bundle.module`
/// needs the file inside the test target, i.e. a copy that could drift.
/// Simulator runs see the host filesystem; anywhere it can't be read, the
/// test skips with a message instead of passing silently.
final class SinuaGoldenTests: XCTestCase {
    private static let dotStride = 8

    private func loadGolden() throws -> [String: Any] {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // CoreEngineTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // ios
            .deletingLastPathComponent()  // packages
            .deletingLastPathComponent()  // repo root
            .appendingPathComponent("spec/sinua-golden.json")
        guard let data = try? Data(contentsOf: url) else {
            throw XCTSkip("spec/sinua-golden.json not readable at \(url.path) (device run?)")
        }
        return try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func nums(_ v: Any?) -> [Double] {
        (v as? [Any] ?? []).map { ($0 as? NSNumber)?.doubleValue ?? .nan }
    }

    /// Mirrors `nearest_match_ok` in sinua_golden.rs.
    private func nearestMismatch(_ got: [[Double]], _ exp: [[Double]], _ tol: Double) -> String? {
        var used = [Bool](repeating: false, count: exp.count)
        for (i, g) in got.enumerated() {
            var best = -1
            var bestD = Double.infinity
            for (j, e) in exp.enumerated() where !used[j] {
                let d = zip(g, e).reduce(0.0) { $0 + ($1.0 - $1.1) * ($1.0 - $1.1) }
                if d < bestD { (best, bestD) = (j, d) }
            }
            if best < 0 { return "dot[\(i)] has no golden dot left" }
            used[best] = true
            for k in 0..<Self.dotStride where abs(g[k] - exp[best][k]) >= tol {
                return "dot[\(i)] field \(k): expected \(exp[best][k]), got \(g[k])"
            }
        }
        return nil
    }

    func testAllSinuaGoldenCasesMatch() throws {
        let golden = try loadGolden()
        let tol = try XCTUnwrap(golden["tolerance"] as? Double)
        // spec 1.1.0 added line saturation/hue (stride 7 -> 9) and colorMode.
        let lineStride = (golden["specVersion"] as? String ?? "1.0.0") >= "1.1.0" ? 9 : 7
        let cases = try XCTUnwrap(golden["cases"] as? [[String: Any]])
        XCTAssertFalse(cases.isEmpty)

        for c in cases {
            let key = c["key"] as? String ?? "?"
            let overrides = (c["overrides"] as? [String: Any] ?? [:])
                .mapValues { ($0 as? NSNumber)?.doubleValue ?? .nan }
            let f = try XCTUnwrap(
                CoreEngine.frameWithOverrides(
                    state: try XCTUnwrap(c["state"] as? String),
                    size: UInt32(try XCTUnwrap(c["size"] as? Int)),
                    t: try XCTUnwrap(c["t"] as? Double),
                    overrides: overrides),
                "\(key): state did not resolve")

            XCTAssertEqual(f.dots.count, c["dotCount"] as? Int, "\(key): dot count")
            XCTAssertEqual(f.lines.count, c["lineCount"] as? Int, "\(key): line count")
            XCTAssertEqual(f.polylines.count, c["polylineCount"] as? Int, "\(key): polyline count")
            guard f.dots.count == c["dotCount"] as? Int,
                f.lines.count == c["lineCount"] as? Int,
                f.polylines.count == c["polylineCount"] as? Int
            else { continue }

            let got = f.dots.map { [$0.x, $0.y, $0.z, $0.r, $0.white, $0.a, $0.saturation, $0.hue] }
            let flat = nums(c["dots"])
            let exp = stride(from: 0, to: flat.count, by: Self.dotStride).map {
                Array(flat[$0..<$0 + Self.dotStride])
            }
            let strict = zip(got, exp).allSatisfy { g, e in zip(g, e).allSatisfy { abs($0 - $1) < tol } }
            if !strict, let err = nearestMismatch(got, exp, tol) {
                XCTFail("\(key): \(err)")
            }

            if let mode = c["colorMode"] as? String {
                XCTAssertEqual(f.colorMode == .fixed ? "fixed" : "ink", mode, "\(key): colorMode")
            }
            let lines = nums(c["lines"])
            for (i, l) in f.lines.enumerated() {
                let row = [l.x1, l.y1, l.x2, l.y2, l.white, l.a, l.w, l.saturation, l.hue]
                for k in 0..<lineStride {
                    XCTAssertEqual(row[k], lines[i * lineStride + k], accuracy: tol, "\(key): line[\(i)].\(k)")
                }
            }
            let polys = c["polylines"] as? [[String: Any]] ?? []
            for (i, (p, g)) in zip(f.polylines, polys).enumerated() {
                let style = nums(g["style"])
                for (k, v) in [p.white, p.a, p.w, p.saturation, p.hue].enumerated() {
                    XCTAssertEqual(v, style[k], accuracy: tol, "\(key): polyline[\(i)].style[\(k)]")
                }
                let pts = nums(g["points"])
                XCTAssertEqual(pts.count, p.points.count * 2, "\(key): polyline[\(i)] vertex count")
                guard pts.count == p.points.count * 2 else { continue }
                for (j, q) in p.points.enumerated() {
                    XCTAssertEqual(q.x, pts[j * 2], accuracy: tol, "\(key): polyline[\(i)].pt[\(j)].x")
                    XCTAssertEqual(q.y, pts[j * 2 + 1], accuracy: tol, "\(key): polyline[\(i)].pt[\(j)].y")
                }
                // spec 1.6.0: per-vertex hues, absent = none.
                let hues = nums(g["hues"])
                XCTAssertEqual(p.hues.count, hues.count, "\(key): polyline[\(i)] hue count")
                for (j, (h, gh)) in zip(p.hues, hues).enumerated() {
                    XCTAssertEqual(h, gh, accuracy: tol, "\(key): polyline[\(i)].hues[\(j)]")
                }
            }

            // spec 1.2.0: fills and effect runs, only on cases that carry them.
            let gfills = c["fills"] as? [[String: Any]] ?? []
            XCTAssertEqual(f.fills.count, gfills.count, "\(key): fill count")
            for (i, (x, g)) in zip(f.fills, gfills).enumerated() {
                let cmp = { (label: String, got: [Double], exp: [Double]) in
                    XCTAssertEqual(got.count, exp.count, "\(key): fill[\(i)].\(label) length")
                    for (k, (u, v)) in zip(got, exp).enumerated() {
                        XCTAssertEqual(u, v, accuracy: tol, "\(key): fill[\(i)].\(label)[\(k)]")
                    }
                }
                cmp("style", [x.white, x.a, x.saturation, x.hue, x.blur, Double(x.blend)], nums(g["style"]))
                cmp("points", x.points.flatMap { [$0.x, $0.y] }, nums(g["points"]))
                // spec 1.3.0: holes (absent = none).
                let gh = g["holes"] as? [Any] ?? []
                XCTAssertEqual(x.holes.count, gh.count, "\(key): fill[\(i)] hole count")
                for (h, (ring, gring)) in zip(x.holes, gh).enumerated() {
                    cmp("holes[\(h)]", ring.flatMap { [$0.x, $0.y] }, nums(gring))
                }
                let gg = g["gradient"] as? [String: Any]
                XCTAssertEqual(x.gradient == nil, gg == nil, "\(key): fill[\(i)] gradient")
                if let xg = x.gradient, let gg {
                    XCTAssertEqual(Int(xg.kind), gg["kind"] as? Int, "\(key): fill[\(i)] kind")
                    cmp("gradient.geom", [xg.x0, xg.y0, xg.x1, xg.y1, xg.r], nums(gg["geom"]))
                    cmp(
                        "gradient.stops", xg.stops.flatMap { [$0.offset, $0.white, $0.a, $0.saturation, $0.hue] },
                        nums(gg["stops"]))
                }
            }
            let eff = f.effects.flatMap {
                [Double($0.target), Double($0.start), Double($0.count), $0.blur, Double($0.blend)]
            }
            let geff = nums(c["effects"])
            XCTAssertEqual(eff.count, geff.count, "\(key): effect count")
            for (k, (u, v)) in zip(eff, geff).enumerated() {
                XCTAssertEqual(u, v, accuracy: tol, "\(key): effects[\(k)]")
            }
        }
    }

    /// Every pattern in `spec/parameters.json` resolves through the FFI. This was
    /// a hand-written list of the 25 non-ported states; the catalog is pinned to the engine's presets by `catalog.rs`, so
    /// reading it here means a new pattern is checked without anyone listing it.
    func testEveryCatalogPatternResolves() throws {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // CoreEngineTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // ios
            .deletingLastPathComponent()  // packages
            .deletingLastPathComponent()  // repo root
            .appendingPathComponent("spec/parameters.json")
        guard let data = try? Data(contentsOf: url) else {
            throw XCTSkip("spec/parameters.json not readable at \(url.path) (device run?)")
        }
        let root = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        let objects = try XCTUnwrap(root["objects"] as? [[String: Any]])
        let states = objects.flatMap {
            ($0["patterns"] as? [[String: Any]] ?? []).compactMap { $0["id"] as? String }
        }
        XCTAssertGreaterThanOrEqual(
            states.count, 34, "only \(states.count) patterns read -- the file or the loader moved")
        for state in states {
            XCTAssertNotNil(CoreEngine.frame(state: state, size: 64, t: 1.0), "\(state) should resolve")
        }
        // The control: the check can fail, so the loop above is not vacuous.
        XCTAssertNil(CoreEngine.frame(state: "not-a-real-state", size: 64, t: 0.0))
    }
}
