#!/usr/bin/env node
// Writes `dist-dev/` for `@sinua/core/dev` (design note 33): the compiled default
// API with every import of the default wasm pointed at the dev wasm, plus the entry
// that adds the dev functions. A tool that imports from `@sinua/core/dev` (or
// aliases `@sinua/core` to it, as the Studio does) then runs one engine instance.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "dist");
const out = join(root, "dist-dev");
const FROM = "../pkg/sinua_core_inline.js";
const TO = "../pkg-dev/sinua_core_inline.js";

rmSync(out, { recursive: true, force: true });
mkdirSync(out);
let rewritten = 0;
for (const f of readdirSync(src)) {
  if (!/\.(js|d\.ts)$/.test(f)) continue;
  const text = readFileSync(join(src, f), "utf8");
  const next = text.split(`"${FROM}"`).join(`"${TO}"`);
  if (next !== text) rewritten++;
  writeFileSync(join(out, f), next);
}
if (rewritten === 0) throw new Error(`dev-entry: no file imports ${FROM}; did the layout change?`);
const entry = `// Generated by packages/core/scripts/dev-entry.mjs -- do not edit.
// @sinua/core/dev: the whole default API plus the Studio / dev functions, on one
// (dev) wasm. See src/dev.ts.
export * from "./index.js";
export * from "./dev.js";
`;
writeFileSync(join(out, "dev-entry.js"), entry);
writeFileSync(join(out, "dev-entry.d.ts"), entry);
console.log(`dev-entry: dist-dev/ (${rewritten} modules pointed at the dev wasm)`);
