#!/usr/bin/env node
// Post-processes wasm-pack's `--target web` output (pkg/) so @sinua/core
// loads in any bundler with no wasm config (Angular CLI with Zone.js, webpack
// without asyncWebAssembly, a plain <script type="module">, node without flags):
//   - pkg/sinua_core_inline.js: the wasm as DEFLATE+base64, inflated (fflate,
//     bundled in) and initSync()'d at module load, re-exporting the glue, so the
//     API stays synchronous;
//   - the glue's default `new URL('…_bg.wasm', import.meta.url)` fallback is
//     removed, so bundlers don't also emit the (unused) 729 KB file;
//   - pkg/.gitignore (wasm-pack writes `*`) is removed: npm pack honours it
//     and would otherwise ship no wasm at all;
//   - pkg/package.json is removed: its `sideEffects` list let bundlers tree-shake
//     the inline module's initSync() away.
// Run by `npm run build:wasm`. docs/fx-view.md, *Bundlers*.
import { readFileSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { deflateRawSync } from "node:zlib";
import { buildSync } from "esbuild";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = join(dirname(fileURLToPath(import.meta.url)), "../pkg");
const NAME = "sinua_core";

const gluePath = join(PKG, `${NAME}.js`);
const glue = readFileSync(gluePath, "utf8");
if (!glue.includes("function initSync(")) throw new Error("inline-wasm: expected wasm-pack --target web output (no initSync in the glue)");
const fallback = /\n\s*if \(module_or_path === undefined\) \{\n\s*module_or_path = new URL\('[^']+\.wasm', import\.meta\.url\);\n\s*\}/;
const stripped = glue.replace(
  fallback,
  "\n    if (module_or_path === undefined) {\n        throw new Error('sinua: the wasm is inlined; import sinua_core_inline.js');\n    }"
);
if (stripped === glue && glue.includes("import.meta.url")) throw new Error("inline-wasm: couldn't strip the glue's import.meta.url fallback (wasm-bindgen output changed?)");
writeFileSync(gluePath, stripped);

// Raw DEFLATE, then base64: ~330 KiB instead of ~950 KiB of plain base64,
// which also keeps apps under Angular's default 1 MB initial-bundle budget.
const wasm = readFileSync(join(PKG, `${NAME}_bg.wasm`));
const b64 = deflateRawSync(wasm, { level: 9 }).toString("base64");
const entry = `// Generated by packages/core/scripts/inline-wasm.mjs -- do not edit.
// The engine's wasm (raw DEFLATE, base64), inflated and instantiated synchronously
// on import. The inflater is fflate (MIT, see THIRD_PARTY_LICENSES), bundled in.
import { inflateSync } from "fflate";
import { initSync } from "./${NAME}.js";

const WASM_DEFLATE_BASE64 = "${b64}";

function decode(b64) {
  if (typeof atob === "function") {
    const s = atob(b64);
    const out = new Uint8Array(s.length);
    for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(b64, "base64"));
}

initSync({ module: inflateSync(decode(WASM_DEFLATE_BASE64), { out: new Uint8Array(${wasm.length}) }) });

export * from "./${NAME}.js";
`;
// Bundle fflate in (a plain <script type="module"> can't resolve bare imports);
// the glue stays a sibling module.
const bundled = buildSync({
  stdin: { contents: entry, resolveDir: PKG, sourcefile: `${NAME}_inline.js` },
  bundle: true,
  format: "esm",
  platform: "neutral",
  external: [`./${NAME}.js`],
  legalComments: "inline",
  write: false,
  logLevel: "error",
});
writeFileSync(join(PKG, `${NAME}_inline.js`), bundled.outputFiles[0].text);
writeFileSync(join(PKG, `${NAME}_inline.d.ts`), `export * from "./${NAME}.js";\n`);

// Stale leftovers of the old --target bundler output, wasm-pack's ignore-all file, and
// wasm-pack's pkg/package.json: its `"sideEffects": ["./snippets/*"]` tells bundlers the
// inline module is side-effect-free, so esbuild / Rollup (every Vite production build)
// drop it together with its initSync() -- the first engine call then throws.
for (const f of [".gitignore", `${NAME}_bg.js`, "package.json"]) {
  const p = join(PKG, f);
  if (existsSync(p)) rmSync(p);
}
console.log(`inline-wasm: ${NAME}_inline.js (${(b64.length / 1024).toFixed(0)} KiB base64)`);
