// TypeScript bridge over the Sinua Rust geometry engine.
//
// `frame_json` (generated by wasm-bindgen from `crates/core_engine`) is the
// only FFI surface: a JSON string over the wire, not a zero-copy buffer --
// same tradeoff as the wasm smoke harness, revisit only if a real perf
// ceiling shows up. Everything below is a typed wrapper around it; the
// actual geometry lives in Rust and is proven against
// `spec/orbs-golden.json` in `crates/core_engine/tests/golden.rs`.

import {
  frame_json,
  frame_json_with_overrides,
  frame_transition_json,
  frame_from_fx_spec_json,
  fx_color_to_hsl_json,
  estimate_cost_json,
  fx_spec_cost_json,
  liquid_suitability_json,
  particle_defaults_json,
  parameter_catalog_json,
  check_overrides_json,
  voice_state_profile_json,
} from "../pkg/sinua_core_inline.js";
import type { ReactiveTarget } from "./reactive.js";
// Frames cross the wasm boundary packed (one Float64Array), not as JSON:
// 8-18x faster in node (bench/transport.mjs), bit-identical
// (test/packed.test.mjs). The `*_json` exports stay for compatibility.
import { framePacked, frameFromFxSpecPacked, unpackFrame } from "./packed.js";
// The shared wasm wrappers. They live in their own module so `fxPlayer.ts` can
// import them without looping back through this barrel (test/no-import-cycles).
import { resolveFxSpec, specText } from "./engine.js";
export * from "./engine.js";

// The voice -> overrides DX layer (`VoiceSource`, `AgentState`,
// `VoiceOverrides`, ...) -- DOM-free, see ./voice.ts. `.js` in the
// specifier so the emitted ESM also resolves under plain node, not only
// under a bundler.
export * from "./voice.js";
// Any app value -> one curated Reactive-Input key (`progress`,
// `audioLevel`, `glowStrength`, ...) -- see ./reactive.ts and
// docs/parameters.md's binding contract.
export * from "./reactive.js";

/** Mirrors `orbs::presets::STATES` in Rust. */
export type OrbState =
  | "working"
  | "searching"
  | "solving"
  | "listening"
  | "connecting"
  | "weaving"
  | "composing"
  | "breathing"
  | "shaping"
  // Not part of the original 9 ported states -- see each mode's header
  // comment in `crates/core_engine/src/orbs/modes/` (aurora, webflow,
  // spectrum, sonar, warp, chladni, eclipse, crystallize).
  | "glowing"
  | "drifting"
  | "speaking"
  | "confirming"
  | "initializing"
  | "calibrating"
  | "progressing"
  | "concluding"
  // The "mic muted / connection lost" resting state (`orbs::modes::hush`).
  | "muted"
  // Not `orbs` states at all -- `signal`, a genuinely separate family
  // (see `crates/core_engine/src/signal/mod.rs`). Kept in the same
  // `OrbState` union purely so `frame`/`frameWithOverrides` (whose engine
  // signature spans every family) stay one TS type instead of two -- it
  // does not imply these are more orbs.
  | "signaling"
  | "waveform"
  | "scrolling"
  // ...and a dot-grid LED EQ (`matrix`, audioMotion-analyzer's LED mode).
  | "metering"
  // The `ring` family (`crates/core_engine/src/ring/`): a determinate
  // progress ring, an indeterminate activity spinner, concentric
  // multi-value rings (`progress0..3`, generic -- not Apple's Activity
  // rings), a ring of equal segments (`segmentCount`, `segment0..N`), and
  // an open-bottom value gauge (`sweep`, `fill`, `marker`).
  | "completing"
  | "loading"
  | "tracking"
  | "stepping"
  | "measuring"
  // The `beacon` family (`crates/core_engine/src/beacon/`): discrete-event
  // attention indicators -- a notification ping, a connection pulse with
  // a quality ring, a location halo.
  | "notifying"
  | "reconnecting"
  | "locating"
  // ...a radar sweep over a dot-field scope (`scanning`), and the `((•))`
  // live/transmitting glyph (`broadcasting`).
  | "scanning"
  | "broadcasting"
  // The `core` family (`crates/core_engine/src/core_fx/`): inline
  // "generating..." indicators -- a shimmer sweep and typing dots.
  | "generating"
  | "typing";

/** Mirrors the sizes shipped in `orbs::presets::presets()`. */
export type OrbSize = 20 | 32 | 64;

/** Mirrors `orbs::core::Dot`. `a` is always resolved (never optional). */
export interface Dot {
  x: number;
  y: number;
  z: number;
  r: number;
  /** Ink value: 0 = darkest ink on paper. Mirrored on dark themes by the renderer. */
  white: number;
  a: number;
  /**
   * 0 = achromatic (every ported mode's value) -- the renderer's grayscale
   * ink path applies unchanged. Above 0, blend `white` (as lightness)
   * toward `hue` by this amount. Not part of the upstream port; only
   * `"glowing"` currently sets this above 0 -- see `orbs::core::Dot`'s doc
   * comment in Rust.
   */
  saturation: number;
  /** Hue in degrees `[0, 360)`. Meaningless when `saturation` is `0`. */
  hue: number;
}

/** Mirrors `orbs::core::Line` (the `connecting` state's constellation edges). */
export interface Line {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  white: number;
  a: number;
  w: number;
  /** Same semantics as `Dot.saturation` -- 0 = grey (every mode's default). Added 2026-09-18. */
  saturation: number;
  /** Same semantics as `Dot.hue`. */
  hue: number;
}

/** Mirrors `primitives::Point` -- one vertex of a `Polyline`. */
export interface Point {
  x: number;
  y: number;
}

/**
 * Mirrors `primitives::Polyline`: one continuous stroked path through
 * `points`. Paint contract (see the Rust doc comment for the full story of
 * why this exists -- the per-segment `Line` seams it replaces): polylines
 * draw *first* (then lines, then dots), each as ONE stroked path with round
 * caps and round joins, no fill, stroke width `w`, ink rule identical to
 * `Dot` (`white` as lightness, HSL via `hue` when `saturation > 0`). Only
 * the `signal` family emits these today (`"signaling"` bars, `"waveform"`
 * traces); every `orbs` state leaves the array empty.
 */
export interface Polyline {
  points: Point[];
  white: number;
  a: number;
  w: number;
  saturation: number;
  /** The whole stroke's single hue; with `hues`, the fallback for renderers without per-vertex paint. */
  hue: number;
  /**
   * Per-vertex hue, one per point, or absent = `hue` for the whole stroke.
   * Set by holo / gradient when the vertex hues differ. Paint: each segment
   * a round-capped linear-gradient stroke between its vertices' inks at
   * alpha 1, all in one layer composited once at `a` (docs/engine.md).
   */
  hues?: number[];
}

/** Mirrors `primitives::OrbFrame`: a complete, draw-ready set of instructions. */
/**
 * Mirrors `primitives::ColorMode`: how a renderer resolves lightness per
 * theme. `"ink"` (default) mirrors it on dark themes (`L = 1 - white`);
 * `"fixed"` uses `white` as-is in both themes (Material 3's "fixed"
 * roles). Set by the `colorMode` opt (`apply_color`).
 */
export type ColorMode = "ink" | "fixed";

export interface OrbFrame {
  dots: Dot[];
  lines: Line[];
  polylines: Polyline[];
  /** Paint mode for the whole frame -- see `ColorMode`. */
  colorMode: ColorMode;
  /**
   * Filled shapes (materials phase 1), drawn first -- under polylines,
   * lines, dots. Absent when the frame has none (every frame without a fill
   * opt), so existing frames are unchanged.
   */
  fills?: Fill[];
  /** Paint effects on ranges of dots / lines / polylines (real-blur glow). Absent when none. */
  effects?: EffectRun[];
}

/**
 * Mirrors `primitives::Fill`: a closed polygon. Ink like a `Dot`; with a
 * `gradient`, the stops replace the solid ink and each stop paints at
 * `stop.a * fill.a`. `blur` = Gaussian sigma in engine units (0 = none),
 * `blend` 0 normal / 1 additive. See docs/engine.md, *Paint contract*.
 */
export interface Fill {
  points: Point[];
  /** Inner rings (materials phase 2, liquid): paint outer + holes as one path with the even-odd rule. Absent when none. */
  holes?: Point[][];
  white: number;
  a: number;
  saturation: number;
  hue: number;
  gradient: FillGradient | null;
  blur: number;
  blend: 0 | 1;
}

/** `kind` 0 = linear (x0,y0)->(x1,y1); 1 = radial, centre (x0,y0), radius 0..r. Pad beyond both ends. */
export interface FillGradient {
  kind: 0 | 1;
  x0: number;
  y0: number;
  x1: number;
  y1: number;
  r: number;
  /** 2-3 stops, sorted by offset in 0..1. */
  stops: GradientStop[];
}

export interface GradientStop {
  offset: number;
  white: number;
  /** Relative: painted alpha = stop.a * fill.a. */
  a: number;
  saturation: number;
  hue: number;
}

/** Elements [start, start+count) of list `target` (0 dots, 1 lines, 2 polylines) get blur (sigma) / blend. Never reorders. */
export interface EffectRun {
  target: 0 | 1 | 2;
  start: number;
  count: number;
  blur: number;
  blend: 0 | 1;
}

/**
 * Resolve `(state, size)` and render one frame at time `t` (seconds).
 * Mirrors `core_engine::frame` in Rust -- see `crates/core_engine/src/lib.rs`.
 * Returns `null` for a state/size pair with no preset.
 */
export function frame(state: OrbState, size: OrbSize, t: number): OrbFrame | null {
  return unpackFrame(framePacked(state, size, t));
}

/**
 * `frame` through the old JSON bridge.
 * @deprecated Use `frame` (the packed bridge: same frame, no JSON round trip). Kept only so the parity tests (`test/packed.test.mjs`) and `bench/transport.mjs` can compare the two bridges.
 */
export function frameViaJson(state: OrbState, size: OrbSize, t: number): OrbFrame | null {
  return JSON.parse(frame_json(state, size, t)) as OrbFrame | null;
}

/**
 * `frameWithOverrides` through the old JSON bridge.
 * @deprecated Use `frameWithOverrides` (the packed bridge: same frame, no JSON round trip). Kept only so the parity tests (`test/packed.test.mjs`) and `bench/transport.mjs` can compare the two bridges.
 */
export function frameWithOverridesViaJson(
  state: OrbState,
  size: OrbSize,
  t: number,
  overrides: Partial<Record<string, number>>
): OrbFrame | null {
  return JSON.parse(frame_json_with_overrides(state, size, t, JSON.stringify(overrides))) as OrbFrame | null;
}

/**
 * Real point-by-point morph between two states -- only supported for the
 * one trio that shares the same underlying point lattice: `"glowing"`,
 * `"calibrating"`, `"progressing"` (see
 * `crates/core_engine/src/orbs/modes/transition.rs`'s header for why only
 * these three). Returns `null` for any other pair -- the caller should
 * cross-dissolve two independent `frame()` calls instead (see
 * the Web Studio's `drawCrossDissolve`). `t` is
 * plain elapsed seconds, not scaled by either state's `speed`.
 */
export function frameTransition(
  fromState: OrbState,
  toState: OrbState,
  size: OrbSize,
  t: number,
  blend: number
): OrbFrame | null {
  return JSON.parse(frame_transition_json(fromState, toState, size, t, blend)) as OrbFrame | null;
}

/** Mirrors `core_engine::Resolved` in Rust. */
export interface ResolvedPreset {
  mode: string;
  speed: number;
  opts: Record<string, number>;
}

// ---------------------------------------------------------------- FX Spec --
// One versioned JSON file per object+state (docs/fx-spec.md,
// spec/fx-spec-1.schema.json). Parsing, validation, migration and color
// conversion all live in Rust (`core_engine::fx_spec`); these are thin
// typed wrappers, identical in behaviour to the Swift/Kotlin/RN ones.

/** An FX Spec document (v1). `params` keys are per-state engine opts. */
export interface FxSpec {
  $schema?: string;
  fxSpec: string;
  name?: string;
  description?: string;
  object: "orb" | "signal" | "ring" | "beacon" | "core";
  state: string;
  size?: OrbSize;
  speed?: number;
  /** v1.8: the whole visual's opacity, 0..1 (default 1). A state can patch it. */
  ink?: number;
  color?: FxColor | { value?: FxColor; mix?: number; lightness?: number; mode?: "ink" | "fixed" };
  gradient?: {
    stops: FxColor[];
    angle?: number;
    strength?: number;
    saturation?: number;
    mid?: number;
    path?: "short" | "long";
  };
  materials?: {
    glow?: Partial<Record<"strength" | "radius" | "layers" | "tint" | "hue", number>>;
    noise?: Partial<Record<"strength" | "amplitude" | "scale" | "speed" | "seed", number>>;
    pulse?: Partial<Record<"strength" | "period" | "opacity" | "scale" | "phase", number>>;
  };
  params?: Record<string, number>;
  /** v1.1: app input -> curated Reactive target, keyed by target. */
  bindings?: Partial<Record<ReactiveTarget, FxBinding | null>>;
  /** v1.1: lifecycle key -> design entry, RFC 7396-merged over the top-level design. */
  states?: Record<string, FxStateEntry>;
  /** v1.2 (file-wide): frame cap, and what to shed under low power. */
  performance?: {
    maxFps?: number;
    lowPower?: { maxFps?: number; disable?: ("glow" | "noise" | "pulse" | "gradient")[] };
  };
}

/** v1.1: one binding -- the app's `input` value mapped onto its target (see `bindReactiveInput`). */
export interface FxBinding {
  input: string;
  inputRange?: number[];
  outputRange?: number[];
  curve?: FxCurve | FxCurve[];
}

export type FxCurve = "linear" | "ease" | "easeIn" | "easeOut" | "easeInOut";

/** v1.1: a lifecycle state's design override; `null` deletes an inherited value. */
export type FxStateEntry = {
  [K in
    | "state"
    | "pattern"
    | "speed"
    | "ink"
    | "color"
    | "gradient"
    | "materials"
    | "params"
    | "bindings"]?: unknown;
};

/** v1.1 call context: the current lifecycle key and the app's input values. */
export interface FxContext {
  state?: string;
  inputs?: Record<string, number>;
  /**
   * 1.2: the host is in low power (iOS Low Power Mode, Android Battery
   * Saver, or an app policy) -- apply the spec's `performance.lowPower`.
   */
  lowPower?: boolean;
}

/** `"#RRGGBB"` / `"#RGB"`, or a W3C DTCG (2025.10) color value. */
export type FxColor =
  | string
  | { colorSpace: string; components: [number | "none", number | "none", number | "none"]; alpha?: number; hex?: string };

/** One problem in a spec; `path` is a JSON Pointer (e.g. `/params/colorHeu`). */
export interface FxDiagnostic {
  severity: "error" | "warning";
  path: string;
  message: string;
}

/** Mirrors `core_engine::FxSpecResolved`. `ok` is false if any diagnostic is an error. */
export interface FxSpecResolved {
  ok: boolean;
  state: string;
  size: number;
  /** The spec's own multiplier on the preset's speed. */
  speed: number;
  overrides: Record<string, number>;
  diagnostics: FxDiagnostic[];
  /** v1.1: the `states` key that rendered (`""` = the top-level design). */
  stateKey: string;
  /** v1.1: every key of `states`. */
  stateKeys: string[];
  /** v1.1: bound targets whose input wasn't in `ctx.inputs`. */
  inactiveBindings: string[];
  /** v1.2: the frame cap to honour (low-power cap when `ctx.lowPower`); `null` = host default. */
  maxFps: number | null;
  /** v1.2: materials shed because `ctx.lowPower` was set. */
  disabledMaterials: string[];
}

/** CSS Color 4 HSL (`h` degrees, `0` when `achromatic`; `s`/`l` 0..1) plus the normalized hex. */
export interface FxHsl {
  h: number;
  s: number;
  l: number;
  achromatic: boolean;
  hex: string;
}

/**
 * Render an FX Spec at `elapsed` wall-clock seconds -- the speed scaling
 * (`elapsed * presetSpeed * spec.speed`) is done for you. `null` if the
 * spec has errors; call `resolveFxSpec` to see them.
 */
export function frameFromFxSpec(spec: FxSpec | string, elapsed: number, ctx: FxContext = {}): OrbFrame | null {
  return unpackFrame(frameFromFxSpecPacked(spec, elapsed, ctx));
}

/**
 * `frameFromFxSpec` through the old JSON bridge.
 * @deprecated Use `frameFromFxSpec` (the packed bridge: same frame, no JSON round trip). Kept only so the parity tests (`test/packed.test.mjs`) and `bench/transport.mjs` can compare the two bridges.
 */
export function frameFromFxSpecViaJson(spec: FxSpec | string, elapsed: number, ctx: FxContext = {}): OrbFrame | null {
  return JSON.parse(frame_from_fx_spec_json(specText(spec), elapsed, JSON.stringify(ctx))) as OrbFrame | null;
}

/** A spec color as HSL, via the same conversion the resolver uses. `null` if it doesn't parse. */
export function fxColorToHsl(color: FxColor): FxHsl | null {
  const text = typeof color === "string" ? color : JSON.stringify(color);
  return JSON.parse(fx_color_to_hsl_json(text)) as FxHsl | null;
}

export * from "./fxPlayer.js";
export * from "./packed.js";

// ------------------------------------------------------------------ cost --

/**
 * Render-cost *proxy* (not a measurement): element count and coverage
 * (primitive area / canvas area), the max over fixed sample times, classed
 * light / medium / heavy (thresholds: docs/engine.md, *Cost estimate*).
 * `base*` = the same object with every material off, so
 * `elements - baseElements` is what glow & co. add.
 */
export interface FxCost {
  elements: number;
  dots: number;
  lines: number;
  polylines: number;
  points: number;
  coverage: number;
  class: "light" | "medium" | "heavy";
  baseElements: number;
  baseCoverage: number;
  /** Filled shapes (materials phase 1); counted in `elements`. */
  fills: number;
  /**
   * Blur work proxy: sum over blurred elements of (bbox + 6 sigma)^2-ish x sigma,
   * / canvas area. `medium` above 2.0, `heavy` above 5.0 (docs/engine.md, *Cost estimate*).
   */
  blurLoad: number;
}

/** Cost of `(state, size)` with `overrides` (e.g. the Studio's live knobs). */
export function estimateCost(state: OrbState, size: OrbSize, overrides: Partial<Record<string, number>> = {}): FxCost | null {
  return JSON.parse(estimate_cost_json(state, size, JSON.stringify(overrides))) as FxCost | null;
}

/** Cost of an FX Spec as resolved for `ctx` (state, inputs, lowPower). `null` if it has errors. */
export function fxSpecCost(spec: FxSpec | string, ctx: FxContext = {}): FxCost | null {
  return JSON.parse(fx_spec_cost_json(specText(spec), JSON.stringify(ctx))) as FxCost | null;
}

// ---------------------------------------------------------------- liquid --

/** How well the liquid material suits a state (docs/materials.md, *liquid*). */
export interface LiquidSuitability {
  level: "recommended" | "ok" | "notRecommended";
  /** One short sentence, for a badge tooltip. */
  reason: string;
  /** The state's tuned liquid defaults (applied by the engine when a key is unset). */
  defaults: Record<string, number>;
}

/** Per-state liquid suitability for a Studio badge; `null` for an unknown state. */
export function liquidSuitability(state: OrbState): LiquidSuitability | null {
  return JSON.parse(liquid_suitability_json(state)) as LiquidSuitability | null;
}

// ------------------------------------------------------------- particles --

/**
 * Every particle knob's default on `state` (docs/materials.md, *particles*):
 * the engine-wide defaults with the state's own over them -- ring states
 * rise, scanning attracts, notifying bursts (`particleSync` 1), speaking and
 * signal follow `audioLevel` (`particleAudio` 1), ambient orbs orbit slowly.
 * The engine applies them to unset keys; show them as the knob defaults.
 * `null` for an unknown state.
 */
export function particleDefaults(state: OrbState): Record<string, number> | null {
  return JSON.parse(particle_defaults_json(state)) as Record<string, number> | null;
}

// ------------------------------------------------------------ catalog --

/** One category of the parameter taxonomy (docs/parameters.md). */
export interface ParameterCategory { id: "appearance" | "motion" | "energy" | "material" | "input"; label: string }

/** A discrete choice's engine value, label and FX Spec word. */
export interface ParameterChoice { value: number; label: string; spec: string }

/**
 * One tunable, scoped to the mode (or `shared`) that reads it: the id is
 * `<key>@<scope>`. `key` is the raw engine opt key; `path` is the name
 * FX Spec bindings, typed component props and the docs use
 * (`glow.strength`, `lanes`). `min`/`max` are the valid range
 * (`checkOverrides` enforces it); `uiMin`/`uiMax`/`step` the Studio slider.
 */
export interface ParameterDefinition {
  key: string;
  scope: string;
  path: string;
  label: string;
  description: string;
  category: ParameterCategory["id"];
  /** `value` = app data (a direct component prop); `style` = the look. */
  group: "value" | "style";
  type: "number" | "integer" | "boolean" | "choice" | "number[]";
  min: number;
  max: number;
  uiMin?: number;
  uiMax?: number;
  step?: number;
  unit: string | null;
  fallback: number | null;
  /** `basic` = a Studio knob; `advanced` = engine-only. */
  tier: "basic" | "advanced";
  choices: ParameterChoice[] | null;
  /** Show only while another key has one of these values (Storybook `if`). */
  if: { key: string; in: number[] } | null;
  /** Arrays (`progress[]`, `segment[]`): length bounds and the engine keys they expand to. */
  items?: { minItems: number; maxItems: number; engineKeys: string; uiMin?: number; uiMax?: number; step?: number };
  /** The material section this belongs to (`glow`, `color`, ...), if any. */
  material?: string;
  specPath: string;
  /** Older names that still resolve (the FX Spec 1.7 rename map). */
  aliases: string[];
  deprecated: { replacedBy: string } | null;
}

/** A pattern (the visual, e.g. `breathing`) with its tunables and per-size defaults. */
export interface ParameterPattern {
  id: OrbState;
  label: string;
  mode: string;
  speed: number;
  sizes: OrbSize[];
  params: { ref: string; default: Record<string, number | number[] | null> }[];
  materialDefaults: { particles: Record<string, number>; liquid: Record<string, number> };
}

export interface ParameterObject {
  id: "orb" | "signal" | "ring" | "core" | "beacon";
  label: string;
  component: string;
  patterns: ParameterPattern[];
}

export interface ParameterMaterial {
  id: string;
  label: string;
  description: string;
  specSection: string;
  master: string;
  params: string[];
}

export interface RuntimeInput {
  key: string;
  path: string;
  label: string;
  description: string;
  type: string;
  min?: number;
  max?: number;
  group?: "value" | "style";
  runtime?: boolean;
  items?: { minItems: number; maxItems: number; engineKeys: string };
}

/** The parameter catalog (docs/parameters.md, *Parameter catalog*; `spec/parameters.json`). */
export interface ParameterCatalog {
  catalogVersion: number;
  fxSpec: string;
  categories: ParameterCategory[];
  objects: ParameterObject[];
  definitions: Record<string, ParameterDefinition>;
  materials: ParameterMaterial[];
  runtimeInputs: RuntimeInput[];
  internalKeys: string[];
}

let catalogCache: ParameterCatalog | null = null;

/**
 * The parameter catalog: every object, pattern and tunable, with labels,
 * descriptions, valid/UI ranges, groups, paths and per-size defaults. Rust
 * owns it; this is the same JSON as `spec/parameters.json`. Parsed once.
 */
export function parameterCatalog(): ParameterCatalog {
  return (catalogCache ??= JSON.parse(parameter_catalog_json()) as ParameterCatalog);
}

/**
 * Validates engine overrides for a pattern against the catalog. Warnings
 * only (unknown key with a did-you-mean, out of range, fractional value for
 * a whole-number key, renamed key); the frame renders regardless.
 */
export function checkOverrides(pattern: OrbState, size: OrbSize, overrides: Partial<Record<string, number>>): FxDiagnostic[] {
  return JSON.parse(check_overrides_json(pattern, size, JSON.stringify(overrides))) as FxDiagnostic[];
}

/** The five agent states the voice-state profile knows, in lifecycle order. */
export const VOICE_STATES = ["initializing", "idle", "listening", "thinking", "speaking"] as const;
export type VoiceStateName = (typeof VOICE_STATES)[number];

/** What one agent state does to one pattern (FX Spec 1.8, `spec/voice-state-profile.json`). */
export interface VoiceStateProfile {
  /** Multiplies the pattern's tuned speed. */
  speed: number;
  /** Engine keys to apply -- `ink`, `audioStrength` (negative = the listening inhale), particles, glow. */
  overrides: Record<string, number>;
  /** Which app input drives `audioLevel` here (`micLevel` / `agentVolume`), or null. Not an engine key. */
  audioInput: string | null;
}

/**
 * The built-in behaviour for `state` on `pattern`: one shape stays on
 * screen and the agent's state changes how it moves. `null` for a state
 * outside the voice language, so an app's own state names are left alone.
 *
 * Views use it for plain input (`pattern` + `state`, no spec): merge it
 * *under* your own overrides, so yours win. A spec doesn't need it --
 * `resolveFxSpec` already fills it into a 1.8+ file's voice-state entries.
 */
export function voiceStateProfile(pattern: OrbState | string, state: VoiceStateName | string): VoiceStateProfile | null {
  return JSON.parse(voice_state_profile_json(pattern, state)) as VoiceStateProfile | null;
}
