package dev.sinua.core

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import org.junit.runner.RunWith
import uniffi.core_engine.ColorMode
import uniffi.core_engine.frame
import uniffi.core_engine.frameWithOverrides
import kotlin.math.abs

/**
 * Platform parity against `spec/sinua-golden.json` -- all 210 cases of
 * the 25 states upstream's `spec/orbs-golden.json` doesn't cover, run
 * through the real UniFFI boundary (Kotlin -> JNA -> C -> Rust) on an
 * Android runtime's float/libm. The reference checker is
 * `crates/core_engine/tests/sinua_golden.rs`; the rules mirror it
 * (counts, dots strict with a nearest-neighbour fallback, lines and
 * polylines strict, the file's own tolerance).
 *
 * A cross-platform lock, not a correctness proof: the set was generated by
 * this engine (see docs/testing.md). The file is bundled into the test APK
 * straight from the repo's `spec/` (build.gradle.kts `androidTest` assets)
 * and read with the *instrumentation* context -- `targetContext` would
 * look in the library's main assets.
 */
@RunWith(AndroidJUnit4::class)
class SinuaGoldenTests {
    private val dotStride = 8

    private fun loadGolden(): JSONObject {
        val ctx = InstrumentationRegistry.getInstrumentation().context
        val text = ctx.assets.open("sinua-golden.json").bufferedReader().use { it.readText() }
        return JSONObject(text)
    }

    private fun nums(a: JSONArray): DoubleArray = DoubleArray(a.length()) { a.getDouble(it) }

    /** Mirrors `nearest_match_ok` in sinua_golden.rs. */
    private fun nearestMismatch(got: List<DoubleArray>, exp: List<DoubleArray>, tol: Double): String? {
        val used = BooleanArray(exp.size)
        for ((i, g) in got.withIndex()) {
            var best = -1
            var bestD = Double.POSITIVE_INFINITY
            for ((j, e) in exp.withIndex()) {
                if (used[j]) continue
                var d = 0.0
                for (k in 0 until dotStride) d += (g[k] - e[k]) * (g[k] - e[k])
                if (d < bestD) {
                    best = j
                    bestD = d
                }
            }
            if (best < 0) return "dot[$i] has no golden dot left"
            used[best] = true
            for (k in 0 until dotStride) {
                if (abs(g[k] - exp[best][k]) >= tol) return "dot[$i] field $k: expected ${exp[best][k]}, got ${g[k]}"
            }
        }
        return null
    }

    @Test
    fun allSinuaGoldenCasesMatch() {
        val golden = loadGolden()
        val tol = golden.getDouble("tolerance")
        // spec 1.1.0 added line saturation/hue (stride 7 -> 9) and colorMode.
        val lineStride = if (golden.optString("specVersion", "1.0.0") >= "1.1.0") 9 else 7
        val cases = golden.getJSONArray("cases")
        assertTrue(cases.length() > 0)

        for (ci in 0 until cases.length()) {
            val c = cases.getJSONObject(ci)
            val key = c.getString("key")
            val ov = c.getJSONObject("overrides")
            val overrides = ov.keys().asSequence().associateWith { ov.getDouble(it) }
            val f = frameWithOverrides(c.getString("state"), c.getInt("size").toUInt(), c.getDouble("t"), overrides)
            assertNotNull("$key: state did not resolve", f)
            f!!
            assertEquals("$key: dot count", c.getInt("dotCount"), f.dots.size)
            assertEquals("$key: line count", c.getInt("lineCount"), f.lines.size)
            assertEquals("$key: polyline count", c.getInt("polylineCount"), f.polylines.size)

            val got = f.dots.map { doubleArrayOf(it.x, it.y, it.z, it.r, it.white, it.a, it.saturation, it.hue) }
            val flat = nums(c.getJSONArray("dots"))
            val exp = (flat.indices step dotStride).map { flat.copyOfRange(it, it + dotStride) }
            val strict = got.indices.all { i -> (0 until dotStride).all { k -> abs(got[i][k] - exp[i][k]) < tol } }
            if (!strict) nearestMismatch(got, exp, tol)?.let { fail("$key: $it") }

            if (c.has("colorMode")) {
                val mode = if (f.colorMode == ColorMode.FIXED) "fixed" else "ink"
                assertEquals("$key: colorMode", c.getString("colorMode"), mode)
            }
            val lines = nums(c.getJSONArray("lines"))
            f.lines.forEachIndexed { i, l ->
                val row = doubleArrayOf(l.x1, l.y1, l.x2, l.y2, l.white, l.a, l.w, l.saturation, l.hue)
                for (k in 0 until lineStride) {
                    assertEquals("$key: line[$i].$k", lines[i * lineStride + k], row[k], tol)
                }
            }
            val polys = c.getJSONArray("polylines")
            f.polylines.forEachIndexed { i, p ->
                val g = polys.getJSONObject(i)
                val style = nums(g.getJSONArray("style"))
                doubleArrayOf(p.white, p.a, p.w, p.saturation, p.hue).forEachIndexed { k, v ->
                    assertEquals("$key: polyline[$i].style[$k]", style[k], v, tol)
                }
                val pts = nums(g.getJSONArray("points"))
                assertEquals("$key: polyline[$i] vertex count", pts.size, p.points.size * 2)
                p.points.forEachIndexed { j, q ->
                    assertEquals("$key: polyline[$i].pt[$j].x", pts[j * 2], q.x, tol)
                    assertEquals("$key: polyline[$i].pt[$j].y", pts[j * 2 + 1], q.y, tol)
                }
                // spec 1.6.0: per-vertex hues, absent = none.
                val hues = g.optJSONArray("hues")?.let(::nums) ?: DoubleArray(0)
                assertEquals("$key: polyline[$i] hue count", hues.size, p.hues.size)
                p.hues.forEachIndexed { j, h -> assertEquals("$key: polyline[$i].hues[$j]", hues[j], h, tol) }
            }

            // spec 1.2.0: fills and effect runs, only on cases that carry them.
            val gfills = c.optJSONArray("fills") ?: JSONArray()
            assertEquals("$key: fill count", gfills.length(), f.fills.size)
            f.fills.forEachIndexed { i, x ->
                val g = gfills.getJSONObject(i)
                fun cmp(label: String, got: DoubleArray, exp: DoubleArray) {
                    assertEquals("$key: fill[$i].$label length", exp.size, got.size)
                    got.forEachIndexed { k, v -> assertEquals("$key: fill[$i].$label[$k]", exp[k], v, tol) }
                }
                cmp(
                    "style",
                    doubleArrayOf(x.white, x.a, x.saturation, x.hue, x.blur, x.blend.toDouble()),
                    nums(g.getJSONArray("style")),
                )
                cmp("points", x.points.flatMap { listOf(it.x, it.y) }.toDoubleArray(), nums(g.getJSONArray("points")))
                // spec 1.3.0: holes (absent = none).
                val gh = g.optJSONArray("holes") ?: JSONArray()
                assertEquals("$key: fill[$i] hole count", gh.length(), x.holes.size)
                x.holes.forEachIndexed { h, ring ->
                    cmp("holes[$h]", ring.flatMap { listOf(it.x, it.y) }.toDoubleArray(), nums(gh.getJSONArray(h)))
                }
                val gg = g.optJSONObject("gradient")
                assertEquals("$key: fill[$i] gradient", gg == null, x.gradient == null)
                val xg = x.gradient
                if (xg != null && gg != null) {
                    assertEquals("$key: fill[$i] kind", gg.getInt("kind"), xg.kind.toInt())
                    cmp("gradient.geom", doubleArrayOf(xg.x0, xg.y0, xg.x1, xg.y1, xg.r), nums(gg.getJSONArray("geom")))
                    cmp(
                        "gradient.stops",
                        xg.stops.flatMap {
                            listOf(it.offset, it.white, it.a, it.saturation, it.hue)
                        }.toDoubleArray(),
                        nums(gg.getJSONArray("stops")),
                    )
                }
            }
            val eff = f.effects.flatMap {
                listOf(it.target.toDouble(), it.start.toDouble(), it.count.toDouble(), it.blur, it.blend.toDouble())
            }
            val geff = c.optJSONArray("effects")?.let { nums(it) } ?: DoubleArray(0)
            assertEquals("$key: effect count", geff.size, eff.size)
            eff.forEachIndexed { k, v -> assertEquals("$key: effects[$k]", geff[k], v, tol) }
        }
    }

    /**
     * Every pattern in `spec/parameters.json` (a test asset: build.gradle.kts stages
     * the repo's spec/) resolves through the FFI. This was a hand-written list of
     * the 25 non-ported states; the catalog is
     * pinned to the engine's presets by `catalog.rs`, so a new pattern is checked
     * here without anyone listing it.
     */
    @Test
    fun everyCatalogPatternResolves() {
        val ctx = InstrumentationRegistry.getInstrumentation().context
        val objects = JSONObject(ctx.assets.open("parameters.json").bufferedReader().use { it.readText() })
            .getJSONArray("objects")
        val states = (0 until objects.length()).flatMap { i ->
            val patterns = objects.getJSONObject(i).getJSONArray("patterns")
            (0 until patterns.length()).map { patterns.getJSONObject(it).getString("id") }
        }
        assertTrue("only ${states.size} patterns read -- the asset or the loader moved", states.size >= 34)
        for (state in states) assertNotNull("$state should resolve", frame(state, 64u, 1.0))
        // The control: the check can fail, so the loop above is not vacuous.
        assertNull(frame("not-a-real-state", 64u, 0.0))
    }
}
