// Helpers shared by the emitters. No brand names here: everything comes from `naming`.

export const HEADER_LINES = [
  "Generated by scripts/codegen/generate.mjs from spec/parameters.json -- do not edit.",
  "Regenerate: node scripts/codegen/generate.mjs (CI fails when this file is stale).",
];

export const upperSnake = (camelName) => camelName.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

/** The material groups are identical for every object (all `@shared`); emit them once. */
export function sharedGroups(models) {
  const first = models[0].groups;
  const sig = (gs) => JSON.stringify(gs.map((g) => [g.path, g.children]));
  for (const m of models) {
    if (sig(m.groups) !== sig(first)) throw new Error(`codegen: ${m.object} has different material groups; shared types assume identical ones`);
  }
  return first.map((g) => ({ ...g, props: g.children.map((path) => models[0].props.find((p) => p.path === path)) }));
}

export const flatProps = (model) => model.props.filter((p) => !p.root);

const fmt = (n) => (Number.isInteger(n) ? String(n) : String(n));

/** One-line doc text: description, range, applicable patterns. */
export function docLine(prop, model) {
  const parts = [prop.description?.trim() || prop.label];
  const ranges = Object.values(prop.ranges);
  const uniq = [...new Set(ranges.map((r) => `${r.min}..${r.max}`))];
  if (prop.type === "boolean" || prop.choices) {
    // no numeric range
  } else if (uniq.length === 1 && prop.min != null) {
    parts.push(`Range ${fmt(prop.min)}...${fmt(prop.max)}${prop.unit ? ` (${prop.unit})` : ""}.`);
  } else if (prop.min != null) {
    parts.push(
      "Range " +
        Object.entries(prop.ranges)
          .map(([pat, r]) => `${pat} ${fmt(r.min)}...${fmt(r.max)}`)
          .join(", ") +
        ".",
    );
  }
  if (prop.maxItems != null) parts.push(`Up to ${prop.maxItems} values.`);
  if (!prop.root && prop.patterns.length < model.patterns.length) parts.push(`Patterns: ${prop.patterns.join(", ")}.`);
  return parts.join(" ").replace(/\s+/g, " ");
}
