/**
 * The engine's parameter catalog as plain data: `spec/parameters.json`, copied into
 * lib/generated by scripts/copy-specs.mjs. It's what `parameterCatalog()` from
 * `@sinua/core/dev` returns (plus descriptions), read without loading any wasm, so the
 * landing and the gallery don't carry the dev entry.
 */
import type { ParameterCatalog } from "@sinua/core";
import data from "./generated/parameters.json";

const catalog = data as unknown as ParameterCatalog;

export function parameterCatalog(): ParameterCatalog {
  return catalog;
}
